name: Deploy to Linode

on:
  push:
    branches:
      -main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /opt/my-data &&

          # Create .env file
          if [ ! -f .env ]; then
            echo =${{ secrets.INFLUXDB_ADMIN_USER }} >> .env
            echo API_KEY=${{ secrets.INFLUXDB_ADMIN_PASSWORD }} >> .env
            echo SECRET_KEY=${{ secrets.GF_SECURITU_ADMIN_PASSWORD }} >> .env
          fi

          git pull &&
          docker-compose down &&
          docker-compose pull &&
          docker-compose up -d
